apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      environment: dev

patches:
  - target:
      kind: Service
      name: service-devops
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 54321
