apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flask_service.yml
  - flask.yml
  - redis_service.yml
  - redis.yml

labels:
  - includeSelectors: true
    pairs:
      app: devops-course-2025
